### ISSUE TITLE
Remove unused CSS files and directory

### ISSUE THREAD

**Issue by nselikoff** [thetechtakeover/Movies#1]
It looks like you're not using the css directory or the two files inside of it; if this is the case, you should remove them

**Comment by thetechtakeover** [comment]
I removed the style.css file that was in the folder but I believe I am using the other "all.min" file. That is where the fontawesome icons are associated with.

**Comment by nselikoff** [comment]
I thought so at first, but I don't see it included in your index.html (via `<link...`). Maybe you are supposed to include it though?
