### ISSUE TITLE
Remove commented out code

### ISSUE THREAD

**Issue by nselikoff** [thetechtakeover/Movies#2]
Since you're using git for source control, you can always get back to old versions of your code. So in general, unless there's a pretty good reason, I'd suggest not leaving commented out code in your commits. Here are a couple examples of what I'm talking about:

* https://github.com/thetechtakeover/Movies/blob/master/index.html#L23
* https://github.com/thetechtakeover/Movies/blob/master/style.css#L42

**Comment by thetechtakeover** [comment]
completed
