### ISSUE TITLE
Make fontawesome icons accessible

### ISSUE THREAD

**Issue by nselikoff** [thetechtakeover/Movies#4]
I'm glad you tried out fontawesome, it's great to know how to use libraries like that!

Please review the [Accessibility](https://fontawesome.com/how-to-use/on-the-web/other-topics/accessibility) part of their docs and use `aria-label` and `aria-hidden` to make your icons accessible. For example (taken from the link above):

```html
<a href="path/to/shopping/cart" aria-label="View 3 items in your shopping cart">
  <i aria-hidden="true" class="fas fa-shopping-cart"></i>
</a>
```

**Comment by thetechtakeover** [comment]
completed
